export const GET_GRAPHICS_MARKUP_FETCHING = 'GET_GRAPHICS_MARKUP_FETCHING';
export const GET_GRAPHICS_MARKUP_SUCCESS = 'GET_GRAPHICS_MARKUP_SUCCESS';
export const GET_GRAPHICS_MARKUP_ERROR = 'GET_GRAPHICS_MARKUP_ERROR';

export const SET_PAGE = 'SET_PAGE';
export const SET_SORT_BY = 'SET_SORT_BY';
export const SET_SORT_ORDER = 'SET_SORT_ORDER';
